/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripboardsRouteImport } from './routes/tripboards'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CompanionsRouteImport } from './routes/companions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TSlugRouteImport } from './routes/t.$slug'

const TripboardsRoute = TripboardsRouteImport.update({
  id: '/tripboards',
  path: '/tripboards',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionsRoute = CompanionsRouteImport.update({
  id: '/companions',
  path: '/companions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companions': typeof CompanionsRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/pricing': typeof PricingRoute
  '/tripboards': typeof TripboardsRoute
  '/t/$slug': typeof TSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companions': typeof CompanionsRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/pricing': typeof PricingRoute
  '/tripboards': typeof TripboardsRoute
  '/t/$slug': typeof TSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companions': typeof CompanionsRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/pricing': typeof PricingRoute
  '/tripboards': typeof TripboardsRoute
  '/t/$slug': typeof TSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companions'
    | '/login'
    | '/plan'
    | '/pricing'
    | '/tripboards'
    | '/t/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/companions'
    | '/login'
    | '/plan'
    | '/pricing'
    | '/tripboards'
    | '/t/$slug'
  id:
    | '__root__'
    | '/'
    | '/companions'
    | '/login'
    | '/plan'
    | '/pricing'
    | '/tripboards'
    | '/t/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanionsRoute: typeof CompanionsRoute
  LoginRoute: typeof LoginRoute
  PlanRoute: typeof PlanRoute
  PricingRoute: typeof PricingRoute
  TripboardsRoute: typeof TripboardsRoute
  TSlugRoute: typeof TSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tripboards': {
      id: '/tripboards'
      path: '/tripboards'
      fullPath: '/tripboards'
      preLoaderRoute: typeof TripboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companions': {
      id: '/companions'
      path: '/companions'
      fullPath: '/companions'
      preLoaderRoute: typeof CompanionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanionsRoute: CompanionsRoute,
  LoginRoute: LoginRoute,
  PlanRoute: PlanRoute,
  PricingRoute: PricingRoute,
  TripboardsRoute: TripboardsRoute,
  TSlugRoute: TSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
